[build]
  publish = "docs"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
